### ISSUE TITLE
client.getInbox() error

### ISSUE THREAD

**Issue by algoz098** [joaomirandasa/open-insta#8]
After ready when used getInbox() is throw a error
change https://github.com/joaomirandasa/open-insta/blob/master/src/Client.js#L292
`inboxFetch = await window.openInsta.getInbox();`
to
`inboxFetch = await window.openInsta.Direct.getInbox();`
Fix it

```
Error: Evaluation failed: TypeError: window.openInsta.getInbox is not a function
    at __puppeteer_evaluation_script__:3:49
    at ExecutionContext._evaluateInternal (/Users/artur/Documents/open-insta/node_modules/puppeteer/lib/ExecutionContext.js:115:19)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async ExecutionContext.evaluate (/Users/artur/Documents/open-insta/node_modules/puppeteer/lib/ExecutionContext.js:43:16)
    at async Client.getInbox (/Users/artur/Documents/open-insta/src/Client.js:291:23)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/artur/Documents/open-insta/node_modules/puppeteer/lib/helper.js:105:23)
    at DOMWorld.evaluate (/Users/artur/Documents/open-insta/node_modules/puppeteer/lib/DOMWorld.js:102:24)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/artur/Documents/open-insta/node_modules/puppeteer/lib/helper.js:105:23)
    at Page.evaluate (/Users/artur/Documents/open-insta/node_modules/puppeteer/lib/Page.js:784:47)
    at Page.<anonymous> (/Users/artur/Documents/open-insta/node_modules/puppeteer/lib/helper.js:106:31)
    at Client.getInbox (/Users/artur/Documents/open-insta/src/Client.js:291:42)
    at Client.<anonymous> (/Users/artur/Documents/open-insta/example.js:105:16)
    at Client.emit (events.js:223:5)
    at /Users/artur/Documents/open-insta/src/Client.js:202:26
    at Array.forEach (<anonymous>)
    at /Users/artur/Documents/open-insta/src/Client.js:190:22
    at Page._onBindingCalled (/Users/artur/Documents/open-insta/node_modules/puppeteer/lib/Page.js:509:62)
  -- ASYNC --
    at Page.<anonymous> (/Users/artur/Documents/open-insta/node_modules/puppeteer/lib/helper.js:105:23)
    at Client.getInbox (/Users/artur/Documents/open-insta/src/Client.js:291:42)
    at Client.<anonymous> (/Users/artur/Documents/open-insta/example.js:105:16)
    at Client.emit (events.js:223:5)
    at /Users/artur/Documents/open-insta/src/Client.js:202:26
    at Array.forEach (<anonymous>)
    at /Users/artur/Documents/open-insta/src/Client.js:190:22
    at Page._onBindingCalled (/Users/artur/Documents/open-insta/node_modules/puppeteer/lib/Page.js:509:62)
    at CDPSession.<anonymous> (/Users/artur/Documents/open-insta/node_modules/puppeteer/lib/Page.js:110:58)
    at CDPSession.emit (events.js:223:5)
```

**Comment by Theblood** [comment]
@algoz098 Hello I made a pr of this thanks for that solution #9

**Comment by joaomirandasa** [comment]
Fixed by @Theblood - ThankYou @algoz098 too!
